// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: protobuf/models/road.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Road struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Path *Path  `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
}

func (x *Road) Reset() {
	*x = Road{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_models_road_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Road) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Road) ProtoMessage() {}

func (x *Road) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_models_road_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Road.ProtoReflect.Descriptor instead.
func (*Road) Descriptor() ([]byte, []int) {
	return file_protobuf_models_road_proto_rawDescGZIP(), []int{0}
}

func (x *Road) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Road) GetPath() *Path {
	if x != nil {
		return x.Path
	}
	return nil
}

var File_protobuf_models_road_proto protoreflect.FileDescriptor

var file_protobuf_models_road_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x61, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x38, 0x0a, 0x04, 0x52, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x50, 0x61, 0x74, 0x68, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x73, 0x2d,
	0x66, 0x65, 0x72, 0x72, 0x69, 0x6c, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x61, 0x74, 0x61, 0x6e, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_models_road_proto_rawDescOnce sync.Once
	file_protobuf_models_road_proto_rawDescData = file_protobuf_models_road_proto_rawDesc
)

func file_protobuf_models_road_proto_rawDescGZIP() []byte {
	file_protobuf_models_road_proto_rawDescOnce.Do(func() {
		file_protobuf_models_road_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_models_road_proto_rawDescData)
	})
	return file_protobuf_models_road_proto_rawDescData
}

var file_protobuf_models_road_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_models_road_proto_goTypes = []interface{}{
	(*Road)(nil), // 0: models.Road
	(*Path)(nil), // 1: models.Path
}
var file_protobuf_models_road_proto_depIdxs = []int32{
	1, // 0: models.Road.Path:type_name -> models.Path
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_models_road_proto_init() }
func file_protobuf_models_road_proto_init() {
	if File_protobuf_models_road_proto != nil {
		return
	}
	file_protobuf_models_path_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protobuf_models_road_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Road); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_models_road_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_models_road_proto_goTypes,
		DependencyIndexes: file_protobuf_models_road_proto_depIdxs,
		MessageInfos:      file_protobuf_models_road_proto_msgTypes,
	}.Build()
	File_protobuf_models_road_proto = out.File
	file_protobuf_models_road_proto_rawDesc = nil
	file_protobuf_models_road_proto_goTypes = nil
	file_protobuf_models_road_proto_depIdxs = nil
}
